language: ruby
cache: bundler

install:
  - bundle install

script:
  - bundle exec jekyll build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

